FROM animcogn/face_recognition:cpu

# The rest of this file just runs an example script.

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip3 install --no-cache-dir -r /app/requirements.txt

# Install additional dependencies
RUN apt-get update && \
    apt-get install -y libgl1-mesa-glx libglib2.0-0 && \
    rm -rf /var/lib/apt/lists/*

# Expose port 5000 to outside the container
EXPOSE 5000

# Run app.py when the container launches
CMD ["python", "app.py"]